### ISSUE TITLE
Minecraft Stop Game then you open the inventory then you was in Creative mode

### ISSUE THREAD

**Issue by Titoo8899** [Red-Studio-Ragnarok/FlexiPause#2]
### Describe the suggestion

Hi,
your mod is nice and have a feature what I have miss. But I hope you can this feature make with support then we was in Creative Mode. I mean the Config for add the Stop the game then you open the Inventory. This Feature is nice and help me on Survival all thinks to manage. But I hope you can this feature support not only for Survival gamemode and can add in the next update a support for Creative mode.
Then you this feature with a support for Creative Gamemode can add was it nice and I was happy.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Titoo8899** [comment]
What a hell the Support her is so bad I have hope this Project will in the future very much of update become and have only the Release become and not more. Why answer me not one I have a good idear what in this mod missed.

**Comment by Desoroxxx** [comment]
I do not think that would be related to FlexiPause.

FlexiPause allows you to change which GUI pauses the game.

**Comment by Desoroxxx** [comment]
I may have misunderstood the issue here, feel free to explain again/precise things.

**Comment by Titoo8899** [comment]
My Question is give it a way (command) to stop the game then I open the inventory in Creative? I have the good Config site see of your mod and I was a Fan of the mod Inventory Pause.
Link of the Mod: https://modrinth.com/mod/inventory-pause-cursed

And my question was can I with a command the the game Stop then I open the Inventory and then it a commond give what is it?

I hope you can me a answer give of what.

**Comment by Desoroxxx** [comment]
> Link of the Mod: [modrinth.com/mod/inventory-pause-cursed](https://modrinth.com/mod/inventory-pause-cursed)

FlexiPause already allows you to do this
